name: "Release"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


#on:
#  push:
#    tags:
#      - "v*"

jobs:
  deploy-ios:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Build with Gradle
        run: bundle exec fastlane ios deploy
        env:
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          CERT_REPO: ${{ secrets.CERT_REPO }}
          APPLE_ID_TESTFLIGHT: ${{ secrets.APPLE_ID_TESTFLIGHT }}


  deploy-android:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'release.jks'
          fileDir: './composeApp/'
          encodedString: ${{ secrets.ANDROID_KEYSTORE }}

      - name: Write secret to file
        run: echo "$KEY" > fastlane/play-console-credentials.json
        env:
          KEY: ${{ secrets.PLAY_CONSOLE_CREDENTIALS_JSON }}

      - name: Build with Gradle
        run: bundle exec fastlane android deploy
        env:
          ANDROID_SIGNING_KEY: ${{ secrets.ANDROID_SIGNING_KEY }}
          ANDROID_SIGNING_ALIAS: ${{ secrets.ANDROID_SIGNING_ALIAS }}

  deploy-mac-store:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA_MACOS }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD_MACOS }}

      - name: Decode Runtime Provision Profile
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'runtime.provisionprofile'
          fileDir: './composeApp/'
          encodedString: ${{ secrets.RUNTIME_PROVISIONPROFILE }}

      - name: Decode Embedded Provision Profile
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'embedded.provisionprofile'
          fileDir: './composeApp/'
          encodedString: ${{ secrets.EMBEDDED_PROVISIONPROFILE }}

      - name: Decode Entitlements
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'entitlements.plist'
          fileDir: './composeApp/'
          encodedString: ${{ secrets.ENTITLEMENTS }}

      - name: Build with Gradle
        run: bundle exec fastlane macos deploy_store

  build-mac:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 18

      - name: Install Fastlane
        run: |
          gem install bundler
          bundle install

      - name: Import signing certificate
        uses: apple-actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.SIGNING_CERTIFICATE_P12_DATA_MACOS }}
          p12-password: ${{ secrets.SIGNING_CERTIFICATE_PASSWORD_MACOS }}

      - name: Write secret to file
        run: echo "$KEY" > fastlane/mac-api-key.json
        env:
          KEY: ${{ secrets.APPSTORE_CONNECT_API_JSON }}

      - name: Build with Gradle
        run: bundle exec fastlane macos deploy_dmg

      - name: Upload DMG as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Gridline-dmg
          path: composeApp/build/compose/binaries/main-release/dmg/*.dmg

  release-mac:
    needs: [ build-mac ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: get_version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT

      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "./Gridline-dmg/Gridline-${{ steps.get_version.outputs.version }}.dmg"
          tag: ${{ steps.get_version.outputs.version }}
          overwrite: true
          body: "Release ${{ steps.get_version.outputs.version }}"
            
